### ISSUE TITLE
Improvement: getProcessedList

### ISSUE THREAD

**Issue by nancymi** [Cronusyuan/ThoughtworksSchoolWee3-2#1]
https://github.com/Cronusyuan/ThoughtworksSchoolWee3-2/blob/c90462d6b44a40a3c0b9ecbed4a6c335cd7ea5eb/src/main/java/com/thoughtworks/collection/Add.java#L57

This method could be improved by Java 8 stream operation.

**Comment by Cronusyuan** [comment]
fixed with stream().skip() & stream().limit()
